/*
    This file is to define by com-oplink-device.yang
 */

#ifndef _DSC_COD_H_
#define _DSC_COD_H_

#ifdef __cplusplus
extern "C" {
#endif

#include "DSC_ood.h"

#define MODULE_COD        "com-oplink-device"
#define COD_XPATH_PREFIX  "/" MODULE_COD ":org-openroadm-device"

/* #ifndef __OPER__ */
/*
 * /org-openroadm-device:org-openroadm-device/info
 */
#define COD_XPATH_INFO COD_XPATH_PREFIX "/info"
#define COD_XPATH_NODE_ID      COD_XPATH_INFO LEAF_NODE_ID
#define COD_XPATH_NODE_NUMBER  COD_XPATH_INFO LEAF_NODE_NUMBER
#define COD_XPATH_NODE_TYPE    COD_XPATH_INFO LEAF_NODE_TYPE
#define COD_XPATH_CLLI         COD_XPATH_INFO LEAF_CLLI
#define COD_XPATH_VENDOR       COD_XPATH_INFO LEAF_VENDOR
#define COD_XPATH_MODEL        COD_XPATH_INFO LEAF_MODEL
#define COD_XPATH_SERIAL_ID    COD_XPATH_INFO LEAF_SERIAL_ID
#define COD_XPATH_SW_VER       COD_XPATH_INFO LEAF_SW_VER
#define COD_XPATH_SW_VER_BUILD COD_XPATH_INFO LEAF_SW_VER_BUILD
#define COD_XPATH_SW_LIFECYCLE COD_XPATH_INFO LEAF_LIFECYCLE
#define COD_XPATH_SW_SYS_MODE  COD_XPATH_INFO LEAF_SYS_MODE
#define COD_XPATH_RESET_CAUSE  COD_XPATH_INFO LEAF_RESET_CAUSE

#define COD_XPATH_LIST_MAC     COD_XPATH_INFO "/macAddrs"
#define COD_XPATH_LIST_MAC_ALL COD_XPATH_LIST_MAC "//*"
#define COD_XPATH_MAC_ADDR     COD_XPATH_LIST_MAC "[name='eth%d']" LEAF_MAC_ADDR

/*
 * /org-openroadm-device:org-openroadm-device/shelves[shelf-name]
 */
#define COD_XPATH_LIST_SHELVES        COD_XPATH_PREFIX "/shelves"
#define COD_XPATH_LIST_SHELVES_ALL    COD_XPATH_LIST_SHELVES "//*"

#define COD_XPATH_SHELF_NAME           COD_XPATH_LIST_SHELVES LEAF_SHELF_NAME
#define COD_XPATH_SHELF_ALL            COD_XPATH_LIST_SHELVES "[shelf-name='%s']" "//*"
#define COD_XPATH_SHELF_TYPE           COD_XPATH_LIST_SHELVES "[shelf-name='%s']" LEAF_SHELF_TYPE
#define COD_XPATH_SHELF_RACK           COD_XPATH_LIST_SHELVES "[shelf-name='%s']" LEAF_SHELF_RACK
#define COD_XPATH_SHELF_POSITION       COD_XPATH_LIST_SHELVES "[shelf-name='%s']" LEAF_SHELF_POSITION
#define COD_XPATH_SHELF_LIFECYCLE      COD_XPATH_LIST_SHELVES "[shelf-name='%s']" LEAF_SHELF_LIFECYCLE
#define COD_XPATH_SHELF_ADMIN_STATE    COD_XPATH_LIST_SHELVES "[shelf-name='%s']" LEAF_SHELF_ADMIN_STATE
#define COD_XPATH_SHELF_VENDOR         COD_XPATH_LIST_SHELVES "[shelf-name='%s']" LEAF_SHELF_VENDOR
#define COD_XPATH_SHELF_MODEL          COD_XPATH_LIST_SHELVES "[shelf-name='%s']" LEAF_SHELF_MODEL
#define COD_XPATH_SHELF_SERIAL_ID      COD_XPATH_LIST_SHELVES "[shelf-name='%s']" LEAF_SHELF_SERIAL_ID
#define COD_XPATH_SHELF_COMMON_TYPE    COD_XPATH_LIST_SHELVES "[shelf-name='%s']" LEAF_SHELF_COMMON_TYPE
#define COD_XPATH_SHELF_PRODUCT_CODE   COD_XPATH_LIST_SHELVES "[shelf-name='%s']" LEAF_SHELF_PRODUCT_CODE
#define COD_XPATH_SHELF_MFG_DATE       COD_XPATH_LIST_SHELVES "[shelf-name='%s']" LEAF_SHELF_MFG_DATE
#define COD_XPATH_SHELF_CLEI           COD_XPATH_LIST_SHELVES "[shelf-name='%s']" LEAF_SHELF_CLEI
#define COD_XPATH_SHELF_HW_VER         COD_XPATH_LIST_SHELVES "[shelf-name='%s']" LEAF_SHELF_HW_VER
#define COD_XPATH_SHELF_OPRATNAL_STATE COD_XPATH_LIST_SHELVES "[shelf-name='%s']" LEAF_SHELF_OPRATNAL_STATE
#define COD_XPATH_SHELF_EQPMT_STATE    COD_XPATH_LIST_SHELVES "[shelf-name='%s']" LEAF_SHELF_EQPMT_STATE
#define COD_XPATH_SHELF_RESET_CAUSE    COD_XPATH_LIST_SHELVES "[shelf-name='%s']" "/com-oplink-physical-ext:reset-cause"
#define COD_XPATH_SHELF_IS_PHYSICAL    COD_XPATH_LIST_SHELVES "[shelf-name='%s']" LEAF_SHELF_IS_PHYSICAL
#define COD_XPATH_SHELF_IS_PASSIVE     COD_XPATH_LIST_SHELVES "[shelf-name='%s']" LEAF_SHELF_IS_PASSIVE
#define COD_XPATH_SHELF_FACEPTE_LABEL  COD_XPATH_LIST_SHELVES "[shelf-name='%s']" LEAF_SHELF_FACEPTE_LABEL
#define COD_XPATH_SHELF_DUE_DATE       COD_XPATH_LIST_SHELVES "[shelf-name='%s']" LEAF_SHELF_DUE_DATE

/*
 * /org-openroadm-device:org-openroadm-device/shelves[shelf-name='%s']/slots[slot-name]
 */
#define COD_XPATH_LIST_SHELVE_SLOTS      COD_XPATH_LIST_SHELVES "[shelf-name='%s']" "/slots"
#define COD_XPATH_LIST_SHELVE_SLOTS_ALL  COD_XPATH_LIST_SHELVE_SLOTS "//*"

#define COD_XPATH_SLOT_NAME              COD_XPATH_LIST_SHELVE_SLOTS LEAF_SLOT_NAME
#define COD_XPATH_SLOT_LABEL             COD_XPATH_LIST_SHELVE_SLOTS "[slot-name='%s']" LEAF_SLOT_LABEL
#define COD_XPATH_SLOT_PRVSN_CIRCUIT_PAC COD_XPATH_LIST_SHELVE_SLOTS "[slot-name='%s']" LEAF_SLOT_PRVSN_CIRCUIT_PAC
#define COD_XPATH_SLOT_RESET_CAUSE       COD_XPATH_LIST_SHELVE_SLOTS "[slot-name='%s']" LEAF_SLOT_RESET_CAUSE
#define COD_XPATH_SLOT_STATUS            COD_XPATH_LIST_SHELVE_SLOTS "[slot-name='%s']" LEAF_SLOT_STATUS

/*
 * /org-openroadm-device:org-openroadm-device/circuit-packs[circuit-pack-name]
 */
#define COD_XPATH_LIST_CIRCUIT_PACKS     COD_XPATH_PREFIX "/circuit-packs"
#define COD_XPATH_LIST_CIRCUIT_PACKS_ALL COD_XPATH_LIST_CIRCUIT_PACKS "//*"

#define COD_XPATH_CIRCUIT_PACK_ALL             COD_XPATH_LIST_CIRCUIT_PACKS "[circuit-pack-name='%s']" "//*"
#define COD_XPATH_CIRCUIT_PACK_NAME_ALL        COD_XPATH_LIST_CIRCUIT_PACKS LEAF_CP_NAME
#define COD_XPATH_CIRCUIT_PACK_NAME            COD_XPATH_LIST_CIRCUIT_PACKS "[circuit-pack-name='%s']" LEAF_CP_NAME
#define COD_XPATH_CIRCUIT_PACK_PRODUCT_CODE    COD_XPATH_LIST_CIRCUIT_PACKS "[circuit-pack-name='%s']" LEAF_CP_PRODUCT_CODE
#define COD_XPATH_CIRCUIT_PACK_LIFECYCLE_STATE COD_XPATH_LIST_CIRCUIT_PACKS "[circuit-pack-name='%s']" LEAF_CP_LIFECYCLE_STATE
#define COD_XPATH_CIRCUIT_PACK_ADMIN_STATE     COD_XPATH_LIST_CIRCUIT_PACKS "[circuit-pack-name='%s']" LEAF_CP_ADMIN_STATE
#define COD_XPATH_CIRCUIT_PACK_VENDOR          COD_XPATH_LIST_CIRCUIT_PACKS "[circuit-pack-name='%s']" LEAF_CP_VENDOR
#define COD_XPATH_CIRCUIT_PACK_MODEL           COD_XPATH_LIST_CIRCUIT_PACKS "[circuit-pack-name='%s']" LEAF_CP_MODEL
#define COD_XPATH_CIRCUIT_PACK_SERIAL_ID       COD_XPATH_LIST_CIRCUIT_PACKS "[circuit-pack-name='%s']" LEAF_CP_SERIAL_ID
#define COD_XPATH_CIRCUIT_PACK_COMMON_TYPE     COD_XPATH_LIST_CIRCUIT_PACKS "[circuit-pack-name='%s']" LEAF_CP_COMMON_TYPE
#define COD_XPATH_CIRCUIT_PACK_COMMON_PRODUCT_CODE    COD_XPATH_LIST_CIRCUIT_PACKS "[circuit-pack-name='%s']" LEAF_CP_COMMON_PRODUCT_CODE
#define COD_XPATH_CIRCUIT_PACK_MFG_DATE        COD_XPATH_LIST_CIRCUIT_PACKS "[circuit-pack-name='%s']" LEAF_CP_MFG_DATE
#define COD_XPATH_CIRCUIT_PACK_CLEI            COD_XPATH_LIST_CIRCUIT_PACKS "[circuit-pack-name='%s']" LEAF_CP_CLEI
#define COD_XPATH_CIRCUIT_PACK_HW_VER          COD_XPATH_LIST_CIRCUIT_PACKS "[circuit-pack-name='%s']" LEAF_CP_HW_VER
#define COD_XPATH_CIRCUIT_PACK_OPRATNAL_STATE  COD_XPATH_LIST_CIRCUIT_PACKS "[circuit-pack-name='%s']" LEAF_CP_OPRATNAL_STATE

#define COD_XPATH_CIRCUIT_PACK_EQPMT_STATE     COD_XPATH_LIST_CIRCUIT_PACKS "[circuit-pack-name='%s']" LEAF_CP_EQPMT_STATE
#define COD_XPATH_CIRCUIT_PACK_MODE            COD_XPATH_LIST_CIRCUIT_PACKS "[circuit-pack-name='%s']" LEAF_CP_MODE
#define COD_XPATH_CIRCUIT_PACK_REF_SHELF_NAME  COD_XPATH_LIST_CIRCUIT_PACKS "[circuit-pack-name='%s']" LEAF_CP_REF_SHELF_NAME
#define COD_XPATH_CIRCUIT_PACK_REF_SLOT        COD_XPATH_LIST_CIRCUIT_PACKS "[circuit-pack-name='%s']" LEAF_CP_REF_SLOT
#define COD_XPATH_CIRCUIT_PACK_SERVICE_AFFECT  COD_XPATH_LIST_CIRCUIT_PACKS "[circuit-pack-name='%s']" LEAF_CP_SERVICE_AFFECT

#define COD_XPATH_CP_LIST_FEATURES     COD_XPATH_LIST_CIRCUIT_PACKS "[circuit-pack-name='%s']" "/circuit-pack-features"
#define COD_XPATH_CP_LIST_FEATURES_ALL COD_XPATH_CP_LIST_FEATURES "//*"

#define COD_XPATH_CP_LIST_COMPONENTS     COD_XPATH_LIST_CIRCUIT_PACKS "[circuit-pack-name='%s']" "/circuit-pack-components"
#define COD_XPATH_CP_LIST_COMPONENTS_ALL COD_XPATH_CP_LIST_COMPONENTS "//*"

#define COD_XPATH_CPS_COMPONENT_NAME_ALL     COD_XPATH_CP_LIST_COMPONENTS LEAF_CP_COMPONENT
#define COD_XPATH_CPS_COMPONENT_NAME         COD_XPATH_CP_LIST_COMPONENTS "[component-name='%s']" LEAF_CP_COMPONENT
#define COD_XPATH_CPS_COMPONENT_BOOT         COD_XPATH_CP_LIST_COMPONENTS "[component-name='%s']" LEAF_CP_COMPONENT_BOOT
#define COD_XPATH_CPS_COMPONENT_CURRENT_VER  COD_XPATH_CP_LIST_COMPONENTS "[component-name='%s']" LEAF_CP_COMPONENT_CURRENT_VER
#define COD_XPATH_CPS_COMPONENT_VER_TO_APPLY COD_XPATH_CP_LIST_COMPONENTS "[component-name='%s']" LEAF_CP_COMPONENT_VER_TO_APPLY

#define COD_XPATH_CP_LIST_PORTS           COD_XPATH_LIST_CIRCUIT_PACKS "[circuit-pack-name='%s']" "/ports"
#define COD_XPATH_CP_LIST_PORTS_ALL       COD_XPATH_CP_LIST_PORTS "//*"
#define COD_XPATH_CP_PORT_ID_ALL          COD_XPATH_CP_LIST_PORTS "/port-id"
#define COD_XPATH_CP_PORT_ID              COD_XPATH_CP_LIST_PORTS "[port-id='%s']" LEAF_CP_PORT_ID
#define COD_XPATH_CP_PORT_TYPE            COD_XPATH_CP_LIST_PORTS "[port-id='%s']" LEAF_CP_PORT_TYPE
#define COD_XPATH_CP_PORT_WAVELENGTH_TYPE COD_XPATH_CP_LIST_PORTS "[port-id='%s']" LEAF_CP_PORT_WAVELENGTH_TYPE
#define COD_XPATH_CP_PORT_QUAL            COD_XPATH_CP_LIST_PORTS "[port-id='%s']" LEAF_CP_PORT_QUAL
#define COD_XPATH_CP_DIRECTION            COD_XPATH_CP_LIST_PORTS "[port-id='%s']" LEAF_CP_PORT_DIRECTION

/* #endif */

#ifdef __cplusplus
}
#endif

#endif
