#ifndef _ORG_OPENROADM_COMMON_EQUIPMENT_TYPES_
#define _ORG_OPENROADM_COMMON_EQUIPMENT_TYPES_

#include <stdio.h>

/* org-openroadm-common-equipment-types:optic-types enumeration */
typedef enum en_OPTIC_TYPES
{
    OPTIC_TYPES_NONE = 0,
    OPTIC_TYPES_GRAY,
    OPTIC_TYPES_DWDM,
    OPTIC_TYPES_MAX
} EN_OPTIC_TYPES;

/* org-openroadm-common-equipment-types:equipment-type-enum enumeration */
typedef enum en_EQUIPMENT_TYPE_ENUM
{
    EQUIPMENT_TYPE_ENUM_NONE = 0,
    EQUIPMENT_TYPE_ENUM_EQUIPMENT_TYPE_ENUM,
    EQUIPMENT_TYPE_ENUM_OTHER,
    EQUIPMENT_TYPE_ENUM_POWERSUPPLY,
    EQUIPMENT_TYPE_ENUM_SHELFPROCESSOR,
    EQUIPMENT_TYPE_ENUM_CROSSCONNECT,
    EQUIPMENT_TYPE_ENUM_FAN,
    EQUIPMENT_TYPE_ENUM_ACCESSPANEL,
    EQUIPMENT_TYPE_ENUM_CIRCUITPACK,
    EQUIPMENT_TYPE_ENUM_MAX
} EN_EQUIPMENT_TYPE_ENUM;

#endif
