#ifndef _ORG_OPENROADM_EQUIPMENT_STATES_TYPES_
#define _ORG_OPENROADM_EQUIPMENT_STATES_TYPES_

#include <stdio.h>

#ifdef __cplusplus
extern "C" {
#endif

#define ADMIN_STATE_INSERVICE_STR        "inService"
#define ADMIN_STATE_OUTOFSERVICE_STR     "outOfService"
#define ADMIN_STATE_MAINTENANCE_STR      "maintenance"

/* org-openroadm-equipment-states-types:admin-states enumeration */
typedef enum en_EQPT_ADMIN_STATES
{
    EQPT_ADMIN_STATES_NONE = 0,
    EQPT_ADMIN_STATES_INSERVICE,
    EQPT_ADMIN_STATES_OUTOFSERVICE,
    EQPT_ADMIN_STATES_MAINTENANCE,
    EQPT_ADMIN_STATES_MAX
} EN_EQPT_ADMIN_STATES;

/* org-openroadm-equipment-states-types:states enumeration */
typedef enum en_EQPT_STATES
{
    EQPT_STATES_NONE = 0,
    EQPT_STATES_RESERVED_FOR_FACILITY_PLANNED,
    EQPT_STATES_NOT_RESERVED_PLANNED,
    EQPT_STATES_RESERVED_FOR_MAINTENANCE_PLANNED,
    EQPT_STATES_RESERVED_FOR_FACILITY_UNVALIDATED,
    EQPT_STATES_NOT_RESERVED_UNVALIDATED,
    EQPT_STATES_UNKNOWN_UNVALIDATED,
    EQPT_STATES_RESERVED_FOR_MAINTENANCE_UNVALIDATED,
    EQPT_STATES_RESERVED_FOR_FACILITY_AVAILABLE,
    EQPT_STATES_NOT_RESERVED_AVAILABLE,
    EQPT_STATES_RESERVED_FOR_MAINTENANCE_AVAILABLE,
    EQPT_STATES_RESERVED_FOR_REVERSION_INUSE,
    EQPT_STATES_NOT_RESERVED_INUSE,
    EQPT_STATES_RESERVED_FOR_MAINTENANCE_INUSE,
    EQPT_STATES_MAX
} EN_EQPT_STATES;
#ifdef __cplusplus
}
#endif

#endif
