#ifndef _ORG_OPENROADM_COMMON_STATE_TYPES_
#define _ORG_OPENROADM_COMMON_STATE_TYPES_

#include <stdio.h>

/* org-openroadm-common-state-types:lifecycle-state enumeration */
typedef enum en_LIFECYCLE_STATE
{
    LIFECYCLE_STATE_NONE = 0,
    LIFECYCLE_STATE_DEPLOYED,
    LIFECYCLE_STATE_PLANNED,
    LIFECYCLE_STATE_MAINTENANCE,
    LIFECYCLE_STATE_DEPLOYING,
    LIFECYCLE_STATE_UNDEPLOYING,
    LIFECYCLE_STATE_UNDEPLOYED,
    LIFECYCLE_STATE_PROPOSED,
    LIFECYCLE_STATE_DRAFT,
    LIFECYCLE_STATE_DEPLOY_FAILED,
    LIFECYCLE_STATE_UNDEPLOY_FAILED,
    LIFECYCLE_STATE_DEPLOYED_AUGMENTED,
    LIFECYCLE_STATE_DEPLOYED_UPDATING,
    LIFECYCLE_STATE_MAX
} EN_LIFECYCLE_STATE;

/* org-openroadm-common-state-types:state enumeration */
typedef enum en_STATE
{
    STATE_NONE = 0,
    STATE_INSERVICE,
    STATE_OUTOFSERVICE,
    STATE_DEGRADED,
    STATE_MAX
} EN_STATE;

#define OPERATIONAL_STATE_INSERVICE_STR     "inService"
#define OPERATIONAL_STATE_OUTOFSERVICE_STR  "outOfService"
#define OPERATIONAL_STATE_DEGRADED_STR      "degraded"


#endif
