#ifndef _ORG_OPENROADM_COMMON_ALARM_PM_TYPES_
#define _ORG_OPENROADM_COMMON_ALARM_PM_TYPES_

#include <stdio.h>

/* org-openroadm-common-alarm-pm-types:direction enumeration */
typedef enum en_CMN_ALM_PM_TYPE_DIRECTION
{
    CMN_ALM_PM_TYPE_DIRECTION_NONE = 0,
    CMN_ALM_PM_TYPE_DIRECTION_TX,
    CMN_ALM_PM_TYPE_DIRECTION_RX,
    CMN_ALM_PM_TYPE_DIRECTION_BIDIRECTIONAL,
    CMN_ALM_PM_TYPE_DIRECTION_NOTAPPLICABLE,
    CMN_ALM_PM_TYPE_DIRECTION_MAX
} EN_CMN_ALM_PM_TYPE_DIRECTION;

/* org-openroadm-common-alarm-pm-types:location enumeration */
typedef enum en_CMN_ALM_PM_TYPE_LOCATION
{
    CMN_ALM_PM_TYPE_LOCATION_NONE = 0,
    CMN_ALM_PM_TYPE_LOCATION_NOTAPPLICABLE,
    CMN_ALM_PM_TYPE_LOCATION_NEAREND,
    CMN_ALM_PM_TYPE_LOCATION_FAREND,
    CMN_ALM_PM_TYPE_LOCATION_MAX
} EN_CMN_ALM_PM_TYPE_LOCATION;

#endif
