#ifndef _ORG_OPENROADM_COMMON_TYPES_
#define _ORG_OPENROADM_COMMON_TYPES_

#include <stdio.h>

/* org-openroadm-common-types:severity enumeration */
typedef enum en_SEVERITY
{
    SEVERITY_NONE = 0,
    SEVERITY_CRITICAL,
    SEVERITY_MAJOR,
    SEVERITY_MINOR,
    SEVERITY_WARNING,
    SEVERITY_CLEAR,
    SEVERITY_INDETERMINATE,
    SEVERITY_MAX
} EN_SEVERITY;

/* org-openroadm-common-types:activate-notification-type enumeration */
typedef enum en_ACTIVATE_NOTIFICATION_TYPE
{
    ACTIVATE_NOTIFICATION_TYPE_NONE = 0,
    ACTIVATE_NOTIFICATION_TYPE_ACTIVATE,
    ACTIVATE_NOTIFICATION_TYPE_COMMIT,
    ACTIVATE_NOTIFICATION_TYPE_CANCEL,
    ACTIVATE_NOTIFICATION_TYPE_MAX
} EN_ACTIVATE_NOTIFICATION_TYPE;

/* org-openroadm-common-types:rpc-status enumeration */
typedef enum en_RPC_STATUS
{
    RPC_STATUS_NONE = 0,
    RPC_STATUS_SUCCESSFUL,
    RPC_STATUS_FAILED,
    RPC_STATUS_MAX
} EN_RPC_STATUS;

/* org-openroadm-common-types:extended-rpc-status enumeration */
typedef enum en_EXTENDED_RPC_STATUS
{
    EXTENDED_RPC_STATUS_NONE = 0,
    EXTENDED_RPC_STATUS_SUCCESSFUL,
    EXTENDED_RPC_STATUS_FAILED,
    EXTENDED_RPC_STATUS_IN_PROGRESS,
    EXTENDED_RPC_STATUS_MAX
} EN_EXTENDED_RPC_STATUS;

#endif
