swagger: '2.0'
info:
  description: 'This is the first go at creating a swagger API for the Adva OMT device [http://swagger.io](http://swagger.io)'
  version: 0.0.1
  title: Swagger OMT
  termsOfService: 'http://swagger.io/terms/'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: omg.swagger.io
basePath: /
tags:
  - name: OMT
    description: 'Base OMT device '
schemes:
  - http
  - https
paths:
  /omt/config:
    post:
      tags:
        - omt
      summary: push config to the device
      description: push full json object of config to device
      operationId: pushConfig
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: config object to be pushed to the device
          required: true
          schema:
            $ref: '#/definitions/FullConfig'
      responses:
        '200':
          description: successful operation
        '405':
          description: invalid input
    get:
      tags:
        - omt
      summary: get running config from the device
      description: get full json config of the device
      operationId: getConfig
      produces:
        - application/json
      responses:
        '200':
          description: succesful operation
        items:
          $ref: '#/definitions/FullConfig'
  /omt/config/pre-amp/:
    post:
      tags:
        - omt
      summary: push pre-amp config to the device
      operationId: pushConfig
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: config object to be pushed to the device
          required: true
          schema:
            $ref: '#/definitions/Pre-Amp'
      responses:
        '200':
          description: successful operation
        '405':
          description: invalid input
  /omt/config/booster-amp/:
    post:
      tags:
        - omt
      summary: push booster-amp config to the device
      operationId: pushConfig
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: config object to be pushed to the device
          required: true
          schema:
            $ref: '#/definitions/Booster-Amp'
      responses:
        '200':
          description: successful operation
        '405':
          description: invalid input
  /omt/config/system/:
    post:
      tags:
        - omt
      summary: push system config to the device
      operationId: pushConfig
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: config object to be pushed to the device
          required: true
          schema:
            $ref: '#/definitions/System'
      responses:
        '200':
          description: successful operation
        '405':
          description: invalid input
  /omt/inventory:
    get:
      tags:
        - omt
      summary: get device inventory
      description: retrieves inventory information
      operationId: getInventory
      produces:
        - application/json
      responses:
        '200':
          description: successful operation
          $ref: '#/definitions/Inventory'
        '405':
          description: invalid input
  /omt/current-pm-values:
    get:
      tags:
        - omt
      summary: get device pm values
      description: retrieves pm values
      operationId: getPMs
      produces:
        - application/json
      responses:
        '200':
          description: succesful operation
          $ref: '#/definitions/CurrentPmValues'
        '405':
          description: invalid request
  /omt/past-pm-values:
    get:
      tags:
        - omt
      summary: get pm values since last retrieval
      description: retrieves pm values
      operationId: getPms
      produces:
        - application/json
      responses:
        '200':
          description: succesful operation
          $ref: '#/definitions/PmFormat'
        '405':
          description: invalid request
  /omt/current-alarms:
    get:
      tags:
        - omt
      summary: get device alarms
      description: retrieves alarms
      operationId: getAlarms
      produces:
        - application/json
      responses:
        '200':
          description: succesful operation
          $ref: '#/definitions/Alarms'
        '405':
          description: invalid request
  /omt/operations/coldrestart:
    post:
      tags:
        - omt
      summary: coldrestart the entity
      description: initiate coldrestart
      operationId: coldRestart
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: restart state
          required: true
          schema:
            $ref: '#/definitions/Restart'
      responses:
        '200':
          description: successful operation
        '405':
          description: invalid Input
  /omt/operations/warmrestart:
    post:
      tags:
        - omt
      summary: warmrestart the entity
      description: initiate warmrestart
      operationId: warmRestart
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: restart state
          required: true
          schema:
            $ref: '#/definitions/Restart'
      responses:
        '200':
          description: successful operation
        '405':
          description: invalid Input
  /omt/user:
    post:
      tags:
        - omt
      summary: Create user
      description: This can only be done by the logged in user.
      operationId: createUser
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Created login user
          required: true
          schema:
            $ref: '#/definitions/User'
      responses:
        '200':
          description: successful operation
        '400':
          description: failed to add user
    get:
      tags:
        - omt
      summary: get provisioned users on device
      description: this will return provisioned users on device
      operationId: getUsers
      produces:
        - application/json
      responses:
        '200':
          description: succesful operation
          items:
            $ref: '#/definitions/Users'
        '405':
          description: invalid input
  /omt/user/login:
    get:
      tags:
        - omt
      summary: Logs user into the system
      description: logs user in
      operationId: loginUser
      produces:
        - application/json
      parameters:
        - name: username
          in: query
          description: The user name for login
          required: true
          type: string
        - name: password
          in: query
          description: The password for login in clear text
          required: true
          type: string
      responses:
        '200':
          description: successful operation
        '400':
          description: Invalid username/password supplied
  /omt/user/logout:
    get:
      tags:
        - omt
      summary: Logs out current logged in user session
      description: ''
      operationId: logoutUser
      produces:
        - application/xml
      parameters: []
      responses:
        default:
          description: successful operation
  '/omt/user/{username}':
    delete:
      tags:
        - omt
      summary: Delete user
      description: This can only be done by the logged in user.
      operationId: deleteUser
      produces:
        - application/json
      parameters:
        - name: username
          in: path
          description: The name that needs to be deleted
          required: true
          type: string
      responses:
        '400':
          description: Invalid username supplied
        '404':
          description: User not found
  /omt/system/upgrade/software:
    post:
      tags:
      - omt 
      summary: push and upgrade software
      description: will download software then upgrade it
      operationId: Upgrade
      produces: 
        - application/json
      parameters:
        - in: body
          name: load
          description: downloading and loading sw
          required: true
          schema:
            $ref: '#definitions/SoftwareLoad'
      responses:
        '400':
          description: invalid data 
        '200':
          description: successful operation


securityDefinitions:
  petstore_auth:
    type: oauth2
    authorizationUrl: 'http://petstore.swagger.io/oauth/dialog'
    flow: implicit
    scopes:
      'write:pets': modify pets in your account
      'read:pets': read your pets
  api_key:
    type: apiKey
    name: api_key
    in: header
definitions:
  Tag:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
    xml:
      name: Tag
  FullConfig:
    type: object
    properties:
      config:
        type: object
        properties:
          system:
            $ref: '#/definitions/System'
          booster-amp:
            $ref: '#/definitions/Booster-Amp'
          pre-amp:
            $ref: '#/definitions/Pre-Amp'
  Restart:
    type: object
    properties:
      entity:
        type: string
      restart:
        type: boolean
  Users:
    type: object
    properties:
      'user#':
        type: object
        properties:
          username:
            type: string
            title: username
            examples: admin
          password:
            type: string
            title: password
            examples: 12345
          access:
            type: string
            title: access level
            examples: 'full, readonly'
  System:
    type: object
    properties:
      nodename:
        type: string
        title: The hostname
        description: set device hostname
        examples: syd23-bwu11-omt
      gateway:
        type: string
        title: Gateway
        description: set gateway
        examples: 1.1.1.1
      ip-address:
        type: string
        title: The Ip-address .
        description: set node ip.
        examples: 1.1.1.2
      ntp ip 1:
        type: string
        title: The Ntp
        description: set NTP server ip
        examples: 1.1.1.3
      syslog ip 1:
        type: string
        title: The Syslog ip.
        description: set syslog server ip
        examples: 1.1.1.4
      tacacs ip 1:
        type: string
        title: The Tacacs ip
        description: set tacacs server
        examples: 1.1.1.5
  Booster-Amp:
    type: object
    properties:
      target-gain:
        type: number
        title: The Target-gain.
        description: gain setting in DB.
        examples: 16.5
      target-gain-tilt:
        type: integer
        title: 'The Target-gain-tilt '
        description: setting tilt.
        examples: 0
      voa:
        type: integer
        title: The Voa.
        description: setting attenuation.
        examples: 0
      tcdc:
        type: integer
        title: The Tcdc Schema.
        description: setting the dispersion compensation value.
        examples: 100
      state:
        type: string
        title: The State of the amp.
        description: turn amp up or down
        examples: up down
  Pre-Amp:
    type: object
    properties:
      target-gain:
        type: integer
        title: The Target-gain.
        description: to set gain value.
        examples: 13
      target-gain-tilt:
        type: integer
        title: The Target-gain-tilt value.
        description: to set tilt.
        examples: 0
      state:  
        type: string
        title: state of amp.
        description: to turn amp on and off.
        examples:
          - up
          - down
  Inventory:
    type: object
    properties:
      serial-number:
        type: string
        examples: SR12456
      part-number:
        type: string
        examples: PN1234
      software-version:
        type: string
        examples: SV-1.2
      firmware-version:
        type: string
        examples: FV-1.a0
      vendor:
        type: string
        examples: Coca-Cola
  Alarms:
    type: object
    properties:
      alarm:
        type: object
        $ref: '#/definitions/AlarmName'
  AlarmName:
    type: object
    properties:
      alarm-severity:
        type: string
        description: alarm severity
        examples: 'SA, NSA'
      timestamp:
        type: timestamp
        description: timestamp for when alarm raised
        examples: '2016-05-13T02:27:40.261265-04:00'
  CurrentPmValues:
    type: object
    properties:
      timestamp:
        type: timestamp
      mux_rx_pwr:
        type: number
      n_line_rx_pwr:
        type: number
      n_line_tx_pwr:
        type: number
      c_line_rx_pwr:
        type: number
      c_line_tx_pwr:
        type: number
      line_ase:
        type: number
      mux_ase:
        type: number
  SoftwareLoad:
    type: object
    properties:
      entity:
        type: string
      file_name:
        type: string
      load:
        type: base64
  SyslogFormat:
    type: object
    properties:
      Severity:  
        type: string
        examples: NA or NSA
      Timestamp: 
        type: epoch timestamp
        examples: 1517274053
      MSG string: 
        type: string
        examples: LOS
      EntityId: 
        type: string
        examples: Pre-amp Network Rx
  PmFormat:
    type: object
    properties: 
      UniqueTimestamp#:
        type: object
        properties:
          Mux_rx: 
            type: number
          N_line_rx: 
            type: number
          N_line_tx:
            type: number
          C_line_rx:
            type: number
          C_line_tx:
            type: number
          Line_ase:
            type: number
          Mux_ase:
            type: number

  

      
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
