---
swagger: "2.0"
info:
  description: "YANG definitions of Oplink rpc"
  version: "1.0"
  title: "com-oplink-rpc API"
host: "localhost:1234"
consumes:
- "application/yang-data+json"
produces:
- "application/yang-data+json"
paths:
  /operations/get-apsd-state:
    post:
      tags:
      - "com-oplink-rpc"
      summary: "operates on com.oplink.rpc.GetApsdState"
      description: "operates on com.oplink.rpc.GetApsdState"
      parameters:
      - in: "body"
        name: "com.oplink.rpc.getapsdstate.Input.body-param"
        required: false
        schema:
          properties:
            input:
              $ref: "#/definitions/com.oplink.rpc.getapsdstate.Input"
      responses:
        200:
          description: "Correct response"
          schema:
            $ref: "#/definitions/com.oplink.rpc.GetApsdState"
        201:
          description: "No response"
        400:
          description: "Internal error"
  /operations/get-ocm-raw:
    post:
      tags:
      - "com-oplink-rpc"
      summary: "operates on com.oplink.rpc.GetOcmRaw"
      description: "operates on com.oplink.rpc.GetOcmRaw"
      parameters:
      - in: "body"
        name: "com.oplink.rpc.getocmraw.Input.body-param"
        required: false
        schema:
          properties:
            input:
              $ref: "#/definitions/com.oplink.rpc.getocmraw.Input"
      responses:
        200:
          description: "Correct response"
          schema:
            $ref: "#/definitions/com.oplink.rpc.GetOcmRaw"
        201:
          description: "No response"
        400:
          description: "Internal error"
  /operations/log-hash:
    post:
      tags:
      - "com-oplink-rpc"
      summary: "operates on com.oplink.rpc.LogHash"
      description: "operates on com.oplink.rpc.LogHash"
      parameters:
      - in: "body"
        name: "com.oplink.rpc.loghash.Input.body-param"
        required: false
        schema:
          properties:
            input:
              $ref: "#/definitions/com.oplink.rpc.loghash.Input"
      responses:
        200:
          description: "Correct response"
          schema:
            $ref: "#/definitions/com.oplink.rpc.LogHash"
        201:
          description: "No response"
        400:
          description: "Internal error"
  /operations/ready-trigger:
    post:
      tags:
      - "com-oplink-rpc"
      summary: "operates on com.oplink.rpc.ReadyTrigger"
      description: "operates on com.oplink.rpc.ReadyTrigger"
      parameters:
      - in: "body"
        name: "com.oplink.rpc.readytrigger.Input.body-param"
        required: false
        schema:
          properties:
            input:
              $ref: "#/definitions/com.oplink.rpc.readytrigger.Input"
      responses:
        200:
          description: "Correct response"
          schema:
            $ref: "#/definitions/com.oplink.rpc.ReadyTrigger"
        201:
          description: "No response"
        400:
          description: "Internal error"
  /operations/restore-default:
    post:
      tags:
      - "com-oplink-rpc"
      summary: "operates on com.oplink.rpc.RestoreDefault"
      description: "operates on com.oplink.rpc.RestoreDefault"
      parameters:
      - in: "body"
        name: "com.oplink.rpc.restoredefault.Input.body-param"
        required: false
        schema:
          properties:
            input:
              $ref: "#/definitions/com.oplink.rpc.restoredefault.Input"
      responses:
        200:
          description: "Correct response"
          schema:
            $ref: "#/definitions/com.oplink.rpc.RestoreDefault"
        201:
          description: "No response"
        400:
          description: "Internal error"
  /operations/save-conf:
    post:
      tags:
      - "com-oplink-rpc"
      summary: "operates on com.oplink.rpc.SaveConf"
      description: "operates on com.oplink.rpc.SaveConf"
      parameters:
      - in: "body"
        name: "com.oplink.rpc.saveconf.Input.body-param"
        required: false
        schema:
          properties:
            input:
              $ref: "#/definitions/com.oplink.rpc.saveconf.Input"
      responses:
        200:
          description: "Correct response"
          schema:
            $ref: "#/definitions/com.oplink.rpc.SaveConf"
        201:
          description: "No response"
        400:
          description: "Internal error"
  /operations/set-apsd:
    post:
      tags:
      - "com-oplink-rpc"
      summary: "operates on com.oplink.rpc.SetApsd"
      description: "operates on com.oplink.rpc.SetApsd"
      parameters:
      - in: "body"
        name: "com.oplink.rpc.setapsd.Input.body-param"
        required: false
        schema:
          properties:
            input:
              $ref: "#/definitions/com.oplink.rpc.setapsd.Input"
      responses:
        200:
          description: "Correct response"
          schema:
            $ref: "#/definitions/com.oplink.rpc.SetApsd"
        201:
          description: "No response"
        400:
          description: "Internal error"
  /operations/set-auto-ctrl-ramp:
    post:
      tags:
      - "com-oplink-rpc"
      summary: "operates on com.oplink.rpc.SetAutoCtrlRamp"
      description: "operates on com.oplink.rpc.SetAutoCtrlRamp"
      parameters:
      - in: "body"
        name: "com.oplink.rpc.setautoctrlramp.Input.body-param"
        required: false
        schema:
          properties:
            input:
              $ref: "#/definitions/com.oplink.rpc.setautoctrlramp.Input"
      responses:
        200:
          description: "Correct response"
          schema:
            $ref: "#/definitions/com.oplink.rpc.SetAutoCtrlRamp"
        201:
          description: "No response"
        400:
          description: "Internal error"
definitions:
  com.oplink.rpc.GetApsdState:
    type: "object"
    properties:
      output:
        $ref: "#/definitions/com.oplink.rpc.getapsdstate.Output"
  com.oplink.rpc.GetOcmRaw:
    type: "object"
    properties:
      output:
        $ref: "#/definitions/com.oplink.rpc.getocmraw.Output"
  com.oplink.rpc.LogHash:
    type: "object"
    properties:
      output:
        $ref: "#/definitions/org.openroadm.common.types.RpcResponseStatus"
  com.oplink.rpc.ModuleEnumeration:
    type: "string"
    enum:
    - "PA"
    - "BA"
  com.oplink.rpc.Path:
    type: "string"
    enum:
    - "W"
    - "P"
  com.oplink.rpc.ReadyTrigger:
    type: "object"
    properties:
      output:
        $ref: "#/definitions/org.openroadm.common.types.RpcResponseStatus"
  com.oplink.rpc.RestoreDefault:
    type: "object"
    properties:
      output:
        $ref: "#/definitions/org.openroadm.common.types.RpcResponseStatus"
  com.oplink.rpc.RestoreTypeEnumeration:
    type: "string"
    enum:
    - "all"
    - "optical"
  com.oplink.rpc.SaveConf:
    type: "object"
    properties:
      output:
        $ref: "#/definitions/org.openroadm.common.types.RpcResponseStatus"
  com.oplink.rpc.SaveTypeEnumeration:
    type: "string"
    enum:
    - "all"
    - "optical"
  com.oplink.rpc.SetApsd:
    type: "object"
    properties:
      output:
        $ref: "#/definitions/org.openroadm.common.types.RpcResponseStatus"
  com.oplink.rpc.SetAutoCtrlRamp:
    type: "object"
    properties:
      output:
        $ref: "#/definitions/org.openroadm.common.types.RpcResponseStatus"
  com.oplink.rpc.getapsdstate.Input:
    type: "object"
    properties:
      path:
        $ref: "#/definitions/com.oplink.rpc.Path"
  com.oplink.rpc.getapsdstate.Output:
    allOf:
    - $ref: "#/definitions/org.openroadm.common.types.RpcResponseStatus"
    - type: "object"
      properties:
        apsd-status:
          type: "boolean"
          description: "The actual state of apsd-status. True means that apsd is enabled,\
            \ otherwise means disabled."
          default: false
        enabled:
          type: "boolean"
          description: "The config state of apsd-enabled. True means that apsd is\
            \ enabled, otherwise means disabled."
          default: false
  com.oplink.rpc.getocmraw.Input:
    type: "object"
    properties:
      port:
        type: "string"
  com.oplink.rpc.getocmraw.Output:
    allOf:
    - $ref: "#/definitions/org.openroadm.common.types.RpcResponseStatus"
    - type: "object"
      properties:
        data:
          type: "string"
        length:
          type: "integer"
          format: "int64"
  com.oplink.rpc.loghash.Input:
    type: "object"
    properties:
      process-name:
        type: "string"
      enable:
        type: "boolean"
        default: true
  com.oplink.rpc.readytrigger.Input:
    type: "object"
    properties:
      value:
        type: "integer"
        format: "int64"
      module:
        description: "module; optical-amplfier module only"
        $ref: "#/definitions/com.oplink.rpc.ModuleEnumeration"
  com.oplink.rpc.restoredefault.Input:
    type: "object"
    properties:
      restore-type:
        description: "all-whole device; optical-optical module only"
        $ref: "#/definitions/com.oplink.rpc.RestoreTypeEnumeration"
  com.oplink.rpc.saveconf.Input:
    type: "object"
    properties:
      save-type:
        description: "all:whole device; optical:optical module only"
        $ref: "#/definitions/com.oplink.rpc.SaveTypeEnumeration"
  com.oplink.rpc.setapsd.Input:
    type: "object"
    properties:
      path:
        $ref: "#/definitions/com.oplink.rpc.Path"
      enabled:
        type: "boolean"
        description: "Enable/disable apsd"
        default: false
  com.oplink.rpc.setautoctrlramp.Input:
    type: "object"
    properties:
      path:
        $ref: "#/definitions/com.oplink.rpc.Path"
      interval:
        type: "integer"
        format: "int64"
        description: "interval of ramp proc."
      step:
        type: "string"
        description: "step of ramp proc."
  org.openroadm.common.types.RpcResponseStatus:
    type: "object"
    properties:
      status-message:
        type: "string"
        description: "Gives a more detailed status"
      status:
        description: "Successful or Failed"
        $ref: "#/definitions/org.openroadm.common.types.RpcStatus"
  org.openroadm.common.types.RpcStatus:
    type: "string"
    enum:
    - "Successful"
    - "Failed"
