---
swagger: "2.0"
info:
  description: "This model describes configuration and operational state data\n  \
    \  for  distributed feedback (DFB) laser, deployed as part of a transport\n  \
    \  line system."
  version: "1.0"
  title: "com-oplink-dfb API"
host: "localhost:1234"
consumes:
- "application/yang-data+json"
produces:
- "application/yang-data+json"
paths:
  /data/optical-dfb:
    get:
      tags:
      - "com-oplink-dfb"
      summary: "returns com.oplink.dfb.opticaldfbtop.OpticalDfb"
      description: "Enclosing container for dfbs"
      parameters: []
      responses:
        200:
          description: "com.oplink.dfb.opticaldfbtop.OpticalDfb"
          schema:
            $ref: "#/definitions/com.oplink.dfb.opticaldfbtop.OpticalDfbWrapper"
        400:
          description: "Internal error"
    post:
      tags:
      - "com-oplink-dfb"
      summary: "creates com.oplink.dfb.opticaldfbtop.OpticalDfb"
      description: "Enclosing container for dfbs"
      parameters:
      - in: "body"
        name: "com.oplink.dfb.opticaldfbtop.OpticalDfb.body-param"
        description: "com.oplink.dfb.opticaldfbtop.OpticalDfb to be added to list"
        required: false
        schema:
          $ref: "#/definitions/com.oplink.dfb.opticaldfbtop.OpticalDfbWrapper"
      responses:
        201:
          description: "Object created"
        400:
          description: "Internal error"
        409:
          description: "Object already exists"
    put:
      tags:
      - "com-oplink-dfb"
      summary: "creates or updates com.oplink.dfb.opticaldfbtop.OpticalDfb"
      description: "Enclosing container for dfbs"
      parameters:
      - in: "body"
        name: "com.oplink.dfb.opticaldfbtop.OpticalDfb.body-param"
        description: "com.oplink.dfb.opticaldfbtop.OpticalDfb to be added or updated"
        required: false
        schema:
          $ref: "#/definitions/com.oplink.dfb.opticaldfbtop.OpticalDfbWrapper"
      responses:
        201:
          description: "Object created"
        400:
          description: "Internal error"
        204:
          description: "Object modified"
    delete:
      tags:
      - "com-oplink-dfb"
      summary: "removes com.oplink.dfb.opticaldfbtop.OpticalDfb"
      description: "Enclosing container for dfbs"
      parameters: []
      responses:
        400:
          description: "Internal error"
        204:
          description: "Object deleted"
  /data/optical-dfb/dfbs:
    get:
      tags:
      - "com-oplink-dfb"
      summary: "returns com.oplink.dfb.opticaldfbtop.opticaldfb.Dfbs"
      description: "Enclosing container for list of dfbs"
      parameters: []
      responses:
        200:
          description: "com.oplink.dfb.opticaldfbtop.opticaldfb.Dfbs"
          schema:
            $ref: "#/definitions/com.oplink.dfb.opticaldfbtop.opticaldfb.DfbsWrapper"
        400:
          description: "Internal error"
    post:
      tags:
      - "com-oplink-dfb"
      summary: "creates com.oplink.dfb.opticaldfbtop.opticaldfb.Dfbs"
      description: "Enclosing container for list of dfbs"
      parameters:
      - in: "body"
        name: "com.oplink.dfb.opticaldfbtop.opticaldfb.Dfbs.body-param"
        description: "com.oplink.dfb.opticaldfbtop.opticaldfb.Dfbs to be added to\
          \ list"
        required: false
        schema:
          $ref: "#/definitions/com.oplink.dfb.opticaldfbtop.opticaldfb.DfbsWrapper"
      responses:
        201:
          description: "Object created"
        400:
          description: "Internal error"
        409:
          description: "Object already exists"
    put:
      tags:
      - "com-oplink-dfb"
      summary: "creates or updates com.oplink.dfb.opticaldfbtop.opticaldfb.Dfbs"
      description: "Enclosing container for list of dfbs"
      parameters:
      - in: "body"
        name: "com.oplink.dfb.opticaldfbtop.opticaldfb.Dfbs.body-param"
        description: "com.oplink.dfb.opticaldfbtop.opticaldfb.Dfbs to be added or\
          \ updated"
        required: false
        schema:
          $ref: "#/definitions/com.oplink.dfb.opticaldfbtop.opticaldfb.DfbsWrapper"
      responses:
        201:
          description: "Object created"
        400:
          description: "Internal error"
        204:
          description: "Object modified"
    delete:
      tags:
      - "com-oplink-dfb"
      summary: "removes com.oplink.dfb.opticaldfbtop.opticaldfb.Dfbs"
      description: "Enclosing container for list of dfbs"
      parameters: []
      responses:
        400:
          description: "Internal error"
        204:
          description: "Object deleted"
  /data/optical-dfb/dfbs/dfb/:
    post:
      tags:
      - "com-oplink-dfb"
      summary: "creates com.oplink.dfb.opticaldfbtop.opticaldfb.dfbs.Dfb"
      description: "List of variable optical dfbs present in the device"
      parameters:
      - in: "body"
        name: "com.oplink.dfb.opticaldfbtop.opticaldfb.dfbs.Dfb.body-param"
        description: "com.oplink.dfb.opticaldfbtop.opticaldfb.dfbs.Dfb to be added\
          \ to list"
        required: false
        schema:
          $ref: "#/definitions/com.oplink.dfb.opticaldfbtop.opticaldfb.dfbs.DfbWrapper"
      responses:
        201:
          description: "Object created"
        400:
          description: "Internal error"
        409:
          description: "Object already exists"
  /data/optical-dfb/dfbs/dfb={name}:
    get:
      tags:
      - "com-oplink-dfb"
      summary: "returns com.oplink.dfb.opticaldfbtop.opticaldfb.dfbs.Dfb"
      description: "List of variable optical dfbs present in the device"
      parameters:
      - name: "name"
        in: "path"
        description: "Id of dfb"
        required: true
        type: "string"
      responses:
        200:
          description: "com.oplink.dfb.opticaldfbtop.opticaldfb.dfbs.Dfb"
          schema:
            $ref: "#/definitions/com.oplink.dfb.opticaldfbtop.opticaldfb.dfbs.DfbWrapper"
        400:
          description: "Internal error"
    put:
      tags:
      - "com-oplink-dfb"
      summary: "creates or updates com.oplink.dfb.opticaldfbtop.opticaldfb.dfbs.Dfb"
      description: "List of variable optical dfbs present in the device"
      parameters:
      - name: "name"
        in: "path"
        description: "Id of dfb"
        required: true
        type: "string"
      - in: "body"
        name: "com.oplink.dfb.opticaldfbtop.opticaldfb.dfbs.Dfb.body-param"
        description: "com.oplink.dfb.opticaldfbtop.opticaldfb.dfbs.Dfb to be added\
          \ or updated"
        required: false
        schema:
          $ref: "#/definitions/com.oplink.dfb.opticaldfbtop.opticaldfb.dfbs.DfbWrapper"
      responses:
        201:
          description: "Object created"
        400:
          description: "Internal error"
        204:
          description: "Object modified"
    delete:
      tags:
      - "com-oplink-dfb"
      summary: "removes com.oplink.dfb.opticaldfbtop.opticaldfb.dfbs.Dfb"
      description: "List of variable optical dfbs present in the device"
      parameters:
      - name: "name"
        in: "path"
        description: "Id of dfb"
        required: true
        type: "string"
      responses:
        400:
          description: "Internal error"
        204:
          description: "Object deleted"
  /data/optical-dfb/dfbs/dfb={name}/config:
    get:
      tags:
      - "com-oplink-dfb"
      summary: "returns com.oplink.dfb.OpticalDfbConfig"
      description: "Configuration data for the dfb"
      parameters:
      - name: "name"
        in: "path"
        description: "Id of dfb"
        required: true
        type: "string"
      responses:
        200:
          description: "com.oplink.dfb.OpticalDfbConfig"
          schema:
            $ref: "#/definitions/com.oplink.dfb.OpticalDfbConfigWrapper"
        400:
          description: "Internal error"
    post:
      tags:
      - "com-oplink-dfb"
      summary: "creates com.oplink.dfb.OpticalDfbConfig"
      description: "Configuration data for the dfb"
      parameters:
      - name: "name"
        in: "path"
        description: "Id of dfb"
        required: true
        type: "string"
      - in: "body"
        name: "com.oplink.dfb.OpticalDfbConfig.body-param"
        description: "com.oplink.dfb.OpticalDfbConfig to be added to list"
        required: false
        schema:
          $ref: "#/definitions/com.oplink.dfb.OpticalDfbConfigWrapper"
      responses:
        201:
          description: "Object created"
        400:
          description: "Internal error"
        409:
          description: "Object already exists"
    put:
      tags:
      - "com-oplink-dfb"
      summary: "creates or updates com.oplink.dfb.OpticalDfbConfig"
      description: "Configuration data for the dfb"
      parameters:
      - name: "name"
        in: "path"
        description: "Id of dfb"
        required: true
        type: "string"
      - in: "body"
        name: "com.oplink.dfb.OpticalDfbConfig.body-param"
        description: "com.oplink.dfb.OpticalDfbConfig to be added or updated"
        required: false
        schema:
          $ref: "#/definitions/com.oplink.dfb.OpticalDfbConfigWrapper"
      responses:
        201:
          description: "Object created"
        400:
          description: "Internal error"
        204:
          description: "Object modified"
    delete:
      tags:
      - "com-oplink-dfb"
      summary: "removes com.oplink.dfb.OpticalDfbConfig"
      description: "Configuration data for the dfb"
      parameters:
      - name: "name"
        in: "path"
        description: "Id of dfb"
        required: true
        type: "string"
      responses:
        400:
          description: "Internal error"
        204:
          description: "Object deleted"
  /data/optical-dfb/dfbs/dfb={name}/state:
    get:
      tags:
      - "com-oplink-dfb"
      summary: "returns com.oplink.dfb.opticaldfbtop.opticaldfb.dfbs.dfb.State"
      description: "Operational state data for the dfb"
      parameters:
      - name: "name"
        in: "path"
        description: "Id of dfb"
        required: true
        type: "string"
      responses:
        200:
          description: "com.oplink.dfb.opticaldfbtop.opticaldfb.dfbs.dfb.State"
          schema:
            $ref: "#/definitions/com.oplink.dfb.opticaldfbtop.opticaldfb.dfbs.dfb.StateWrapper"
        400:
          description: "Internal error"
  /data/optical-dfb/dfbs/dfb={name}/state/dfb-port={port-name}:
    get:
      tags:
      - "com-oplink-dfb"
      summary: "returns com.oplink.dfb.opticaldfbstate.DfbPort"
      description: "list of ports with input or output power."
      parameters:
      - name: "name"
        in: "path"
        description: "Id of dfb"
        required: true
        type: "string"
      - name: "port-name"
        in: "path"
        description: "Id of dfb-port"
        required: true
        type: "string"
      responses:
        200:
          description: "com.oplink.dfb.opticaldfbstate.DfbPort"
          schema:
            $ref: "#/definitions/com.oplink.dfb.opticaldfbstate.DfbPortWrapper"
        400:
          description: "Internal error"
  /data/optical-dfb/dfbs/dfb={name}/state/dfb-port={port-name}/input-power:
    get:
      tags:
      - "com-oplink-dfb"
      summary: "returns openconfig.types.AvgMinMaxInstantStatsPrecision2DBm"
      description: "The optical in power of this port in units\n          of 0.01dBm.\
        \ If avg/min/max statistics are not supported,\n          just supply the\
        \ instant value"
      parameters:
      - name: "name"
        in: "path"
        description: "Id of dfb"
        required: true
        type: "string"
      - name: "port-name"
        in: "path"
        description: "Id of dfb-port"
        required: true
        type: "string"
      responses:
        200:
          description: "openconfig.types.AvgMinMaxInstantStatsPrecision2DBm"
          schema:
            $ref: "#/definitions/openconfig.types.AvgMinMaxInstantStatsPrecision2DBmWrapper"
        400:
          description: "Internal error"
  /data/optical-dfb/dfbs/dfb={name}/state/dfb-port={port-name}/output-power:
    get:
      tags:
      - "com-oplink-dfb"
      summary: "returns openconfig.types.AvgMinMaxInstantStatsPrecision2DBm"
      description: "The optical out power of this port in units\n          of 0.01dBm.\
        \ If avg/min/max statistics are not supported,\n          just supply the\
        \ instant value"
      parameters:
      - name: "name"
        in: "path"
        description: "Id of dfb"
        required: true
        type: "string"
      - name: "port-name"
        in: "path"
        description: "Id of dfb-port"
        required: true
        type: "string"
      responses:
        200:
          description: "openconfig.types.AvgMinMaxInstantStatsPrecision2DBm"
          schema:
            $ref: "#/definitions/openconfig.types.AvgMinMaxInstantStatsPrecision2DBmWrapper"
        400:
          description: "Internal error"
definitions:
  com.oplink.dfb.OpticalDfbConfig:
    type: "object"
    properties:
      name:
        type: "string"
        description: "User-defined name assigned to identify a specific dfb\n    \
          \    in the device"
      target-output-power:
        type: "string"
        description: "Power level set on the output of dfb"
      enabled:
        type: "boolean"
        description: "When true, dfb is set to maintain constant output power."
        default: false
  com.oplink.dfb.OpticalDfbConfigWrapper:
    properties:
      config:
        $ref: "#/definitions/com.oplink.dfb.OpticalDfbConfig"
  com.oplink.dfb.OpticalDfbState:
    type: "object"
    properties:
      dfb-port:
        type: "array"
        description: "list of ports with input or output power."
        items:
          $ref: "#/definitions/com.oplink.dfb.opticaldfbstate.DfbPort"
      component:
        type: "string"
        description: "Reference to the system-supplied physical component that\n \
          \       the dfb block is contained within. Multiple\n        dfb blocks\
          \ may be contained within the same\n        physical component."
        x-path: "/oc-platform:components/oc-platform:component/oc-platform:name"
  com.oplink.dfb.opticaldfbstate.DfbPort:
    type: "object"
    properties:
      output-power:
        description: "The optical out power of this port in units\n          of 0.01dBm.\
          \ If avg/min/max statistics are not supported,\n          just supply the\
          \ instant value"
        $ref: "#/definitions/openconfig.types.AvgMinMaxInstantStatsPrecision2DBm"
      input-power:
        description: "The optical in power of this port in units\n          of 0.01dBm.\
          \ If avg/min/max statistics are not supported,\n          just supply the\
          \ instant value"
        $ref: "#/definitions/openconfig.types.AvgMinMaxInstantStatsPrecision2DBm"
      port-name:
        type: "string"
        description: "Reference to system-supplied name of port."
        x-path: "/oc-platform:components/oc-platform:component/oc-platform:name"
  com.oplink.dfb.opticaldfbstate.DfbPortWrapper:
    properties:
      dfb-port:
        $ref: "#/definitions/com.oplink.dfb.opticaldfbstate.DfbPort"
  com.oplink.dfb.opticaldfbtop.OpticalDfb:
    type: "object"
    properties:
      dfbs:
        description: "Enclosing container for list of dfbs"
        $ref: "#/definitions/com.oplink.dfb.opticaldfbtop.opticaldfb.Dfbs"
  com.oplink.dfb.opticaldfbtop.OpticalDfbWrapper:
    properties:
      optical-dfb:
        $ref: "#/definitions/com.oplink.dfb.opticaldfbtop.OpticalDfb"
  com.oplink.dfb.opticaldfbtop.opticaldfb.Dfbs:
    type: "object"
    properties:
      dfb:
        type: "array"
        description: "List of variable optical dfbs present in the device"
        items:
          $ref: "#/definitions/com.oplink.dfb.opticaldfbtop.opticaldfb.dfbs.Dfb"
  com.oplink.dfb.opticaldfbtop.opticaldfb.DfbsWrapper:
    properties:
      dfbs:
        $ref: "#/definitions/com.oplink.dfb.opticaldfbtop.opticaldfb.Dfbs"
  com.oplink.dfb.opticaldfbtop.opticaldfb.dfbs.Dfb:
    type: "object"
    properties:
      name:
        type: "string"
        description: "Reference to the name of the dfb"
        x-path: "../config/name"
      state:
        description: "Operational state data for the dfb"
        $ref: "#/definitions/com.oplink.dfb.opticaldfbtop.opticaldfb.dfbs.dfb.State"
      config:
        description: "Configuration data for the dfb"
        $ref: "#/definitions/com.oplink.dfb.OpticalDfbConfig"
  com.oplink.dfb.opticaldfbtop.opticaldfb.dfbs.DfbWrapper:
    properties:
      dfb:
        $ref: "#/definitions/com.oplink.dfb.opticaldfbtop.opticaldfb.dfbs.Dfb"
  com.oplink.dfb.opticaldfbtop.opticaldfb.dfbs.dfb.State:
    allOf:
    - $ref: "#/definitions/com.oplink.dfb.OpticalDfbConfig"
    - $ref: "#/definitions/com.oplink.dfb.OpticalDfbState"
  com.oplink.dfb.opticaldfbtop.opticaldfb.dfbs.dfb.StateWrapper:
    properties:
      state:
        $ref: "#/definitions/com.oplink.dfb.opticaldfbtop.opticaldfb.dfbs.dfb.State"
  openconfig.types.AvgMinMaxInstantStatsPrecision2DBm:
    allOf:
    - $ref: "#/definitions/openconfig.types.MinMaxTime"
    - $ref: "#/definitions/openconfig.types.StatIntervalState"
    - type: "object"
      properties:
        min:
          type: "string"
          description: "The minimum value of the statistic over the time\n       \
            \ interval."
        avg:
          type: "string"
          description: "The arithmetic mean value of the statistic over the\n    \
            \    time interval."
        max:
          type: "string"
          description: "The maximum value of the statistic over the time interval."
        instant:
          type: "string"
          description: "The instantaneous value of the statistic."
      description: "Common grouping for recording dBm values with 2 decimal\n    \
        \  precision. Values include the instantaneous, average,\n      minimum, and\
        \ maximum statistics.  Statistics are computed\n      and reported based on\
        \ a moving time interval (e.g., the last\n      30s).  If supported by the\
        \ device, the time interval over which\n      the statistics are computed,\
        \ and the times at which the minimum\n      and maximum values occurred, are\
        \ also reported."
  openconfig.types.AvgMinMaxInstantStatsPrecision2DBmWrapper:
    properties:
      input-power:
        $ref: "#/definitions/openconfig.types.AvgMinMaxInstantStatsPrecision2DBm"
  openconfig.types.MinMaxTime:
    type: "object"
    properties:
      max-time:
        type: "integer"
        format: "int32"
        description: "The absolute time at which the maximum value occurred.\n   \
          \      The value is the timestamp in nanoseconds relative to\n         \
          \ the Unix Epoch (Jan 1, 1970 00:00:00 UTC)."
      min-time:
        type: "integer"
        format: "int32"
        description: "The absolute time at which the minimum value occurred.\n   \
          \      The value is the timestamp in nanoseconds relative to\n         \
          \ the Unix Epoch (Jan 1, 1970 00:00:00 UTC)."
  openconfig.types.StatIntervalState:
    type: "object"
    properties:
      interval:
        type: "integer"
        format: "int32"
        description: "If supported by the system, this reports the time interval\n\
          \        over which the min/max/average statistics are computed by\n   \
          \     the system."
