---
swagger: "2.0"
info:
  description: "YANG definitions for optical laser safty"
  version: "1.0"
  title: "com-oplink-laser-safty API"
host: "localhost:1234"
consumes:
- "application/yang-data+json"
produces:
- "application/yang-data+json"
paths:
  /data/laser-safty:
    get:
      tags:
      - "com-oplink-laser-safty"
      summary: "returns com.oplink.laser.safty.lasersaftytop.LaserSafty"
      description: "returns com.oplink.laser.safty.lasersaftytop.LaserSafty"
      parameters: []
      responses:
        200:
          description: "com.oplink.laser.safty.lasersaftytop.LaserSafty"
          schema:
            $ref: "#/definitions/com.oplink.laser.safty.lasersaftytop.LaserSaftyWrapper"
        400:
          description: "Internal error"
    post:
      tags:
      - "com-oplink-laser-safty"
      summary: "creates com.oplink.laser.safty.lasersaftytop.LaserSafty"
      description: "creates com.oplink.laser.safty.lasersaftytop.LaserSafty"
      parameters:
      - in: "body"
        name: "com.oplink.laser.safty.lasersaftytop.LaserSafty.body-param"
        description: "com.oplink.laser.safty.lasersaftytop.LaserSafty to be added\
          \ to list"
        required: false
        schema:
          $ref: "#/definitions/com.oplink.laser.safty.lasersaftytop.LaserSaftyWrapper"
      responses:
        201:
          description: "Object created"
        400:
          description: "Internal error"
        409:
          description: "Object already exists"
    put:
      tags:
      - "com-oplink-laser-safty"
      summary: "creates or updates com.oplink.laser.safty.lasersaftytop.LaserSafty"
      description: "creates or updates com.oplink.laser.safty.lasersaftytop.LaserSafty"
      parameters:
      - in: "body"
        name: "com.oplink.laser.safty.lasersaftytop.LaserSafty.body-param"
        description: "com.oplink.laser.safty.lasersaftytop.LaserSafty to be added\
          \ or updated"
        required: false
        schema:
          $ref: "#/definitions/com.oplink.laser.safty.lasersaftytop.LaserSaftyWrapper"
      responses:
        201:
          description: "Object created"
        400:
          description: "Internal error"
        204:
          description: "Object modified"
    delete:
      tags:
      - "com-oplink-laser-safty"
      summary: "removes com.oplink.laser.safty.lasersaftytop.LaserSafty"
      description: "removes com.oplink.laser.safty.lasersaftytop.LaserSafty"
      parameters: []
      responses:
        400:
          description: "Internal error"
        204:
          description: "Object deleted"
  /data/laser-safty/config:
    get:
      tags:
      - "com-oplink-laser-safty"
      summary: "returns com.oplink.laser.safty.LaserSaftyConfig"
      description: "returns com.oplink.laser.safty.LaserSaftyConfig"
      parameters: []
      responses:
        200:
          description: "com.oplink.laser.safty.LaserSaftyConfig"
          schema:
            $ref: "#/definitions/com.oplink.laser.safty.LaserSaftyConfigWrapper"
        400:
          description: "Internal error"
    post:
      tags:
      - "com-oplink-laser-safty"
      summary: "creates com.oplink.laser.safty.LaserSaftyConfig"
      description: "creates com.oplink.laser.safty.LaserSaftyConfig"
      parameters:
      - in: "body"
        name: "com.oplink.laser.safty.LaserSaftyConfig.body-param"
        description: "com.oplink.laser.safty.LaserSaftyConfig to be added to list"
        required: false
        schema:
          $ref: "#/definitions/com.oplink.laser.safty.LaserSaftyConfigWrapper"
      responses:
        201:
          description: "Object created"
        400:
          description: "Internal error"
        409:
          description: "Object already exists"
    put:
      tags:
      - "com-oplink-laser-safty"
      summary: "creates or updates com.oplink.laser.safty.LaserSaftyConfig"
      description: "creates or updates com.oplink.laser.safty.LaserSaftyConfig"
      parameters:
      - in: "body"
        name: "com.oplink.laser.safty.LaserSaftyConfig.body-param"
        description: "com.oplink.laser.safty.LaserSaftyConfig to be added or updated"
        required: false
        schema:
          $ref: "#/definitions/com.oplink.laser.safty.LaserSaftyConfigWrapper"
      responses:
        201:
          description: "Object created"
        400:
          description: "Internal error"
        204:
          description: "Object modified"
    delete:
      tags:
      - "com-oplink-laser-safty"
      summary: "removes com.oplink.laser.safty.LaserSaftyConfig"
      description: "removes com.oplink.laser.safty.LaserSaftyConfig"
      parameters: []
      responses:
        400:
          description: "Internal error"
        204:
          description: "Object deleted"
  /data/laser-safty/state:
    get:
      tags:
      - "com-oplink-laser-safty"
      summary: "returns com.oplink.laser.safty.lasersaftytop.lasersafty.State"
      description: "returns com.oplink.laser.safty.lasersaftytop.lasersafty.State"
      parameters: []
      responses:
        200:
          description: "com.oplink.laser.safty.lasersaftytop.lasersafty.State"
          schema:
            $ref: "#/definitions/com.oplink.laser.safty.lasersaftytop.lasersafty.StateWrapper"
        400:
          description: "Internal error"
definitions:
  com.oplink.laser.safty.LaserSaftyConfig:
    type: "object"
    properties:
      remote-interlock-enable:
        type: "boolean"
        description: "Turns Remote Interlock enable / disable to the amplifiers."
        default: false
      dummy-admin-key-enable:
        type: "boolean"
        description: "Turns dummy-admin-key enable / disable to the amplifiers."
        default: false
      panel-safe-cmpt-enable:
        type: "boolean"
        description: "Turns panel-safe-cmpt enable / disable to the amplifiers."
        default: false
  com.oplink.laser.safty.LaserSaftyConfigWrapper:
    properties:
      config:
        $ref: "#/definitions/com.oplink.laser.safty.LaserSaftyConfig"
  com.oplink.laser.safty.LaserSaftyState:
    type: "object"
    properties:
      admin-key-on:
        type: "boolean"
        description: "admin key is on(true) or off(false)."
        default: false
      shutter-on:
        type: "boolean"
        description: "Mechanical shutter is closed(true) or open(false)."
        default: false
      lc-present:
        type: "boolean"
        description: "lc is present(true) or absent(false)."
        default: false
      inter-lock-on:
        type: "boolean"
        description: "internal lock is on(true) or off(false)."
        default: false
      lc-door-lock:
        type: "boolean"
        description: "lc door lock is on(true) or off(false)."
        default: false
  com.oplink.laser.safty.lasersaftytop.LaserSafty:
    type: "object"
    properties:
      config:
        $ref: "#/definitions/com.oplink.laser.safty.LaserSaftyConfig"
      state:
        $ref: "#/definitions/com.oplink.laser.safty.lasersaftytop.lasersafty.State"
  com.oplink.laser.safty.lasersaftytop.LaserSaftyWrapper:
    properties:
      laser-safty:
        $ref: "#/definitions/com.oplink.laser.safty.lasersaftytop.LaserSafty"
  com.oplink.laser.safty.lasersaftytop.lasersafty.State:
    allOf:
    - $ref: "#/definitions/com.oplink.laser.safty.LaserSaftyConfig"
    - $ref: "#/definitions/com.oplink.laser.safty.LaserSaftyState"
  com.oplink.laser.safty.lasersaftytop.lasersafty.StateWrapper:
    properties:
      state:
        $ref: "#/definitions/com.oplink.laser.safty.lasersaftytop.lasersafty.State"
