---
swagger: "2.0"
info:
  description: "This model describes the device-level connectivity\n    (e.g., internal\
    \ port-to-port) for optical transport line\n    system elements such as wavelength\
    \ routers (ROADMs) and\n    amplifiers. All connections are uni-directional. Note\
    \ that\n    this model explicitly does not intend to model or provide\n    a path\
    \ to any higher layer topology modeling and is only\n    for modeling internal\
    \ links"
  version: "1.0"
  title: "openconfig-transport-line-connectivity API"
host: "localhost:1234"
consumes:
- "application/yang-data+json"
produces:
- "application/yang-data+json"
paths:
  /data/connections:
    get:
      tags:
      - "openconfig-transport-line-connectivity"
      summary: "returns openconfig.transport.line.connectivity.lineconnectivitytop.Connections"
      description: "Enclosing container for line system connections list"
      parameters: []
      responses:
        200:
          description: "openconfig.transport.line.connectivity.lineconnectivitytop.Connections"
          schema:
            $ref: "#/definitions/openconfig.transport.line.connectivity.lineconnectivitytop.ConnectionsWrapper"
        400:
          description: "Internal error"
    post:
      tags:
      - "openconfig-transport-line-connectivity"
      summary: "creates openconfig.transport.line.connectivity.lineconnectivitytop.Connections"
      description: "Enclosing container for line system connections list"
      parameters:
      - in: "body"
        name: "openconfig.transport.line.connectivity.lineconnectivitytop.Connections.body-param"
        description: "openconfig.transport.line.connectivity.lineconnectivitytop.Connections\
          \ to be added to list"
        required: false
        schema:
          $ref: "#/definitions/openconfig.transport.line.connectivity.lineconnectivitytop.ConnectionsWrapper"
      responses:
        201:
          description: "Object created"
        400:
          description: "Internal error"
        409:
          description: "Object already exists"
    put:
      tags:
      - "openconfig-transport-line-connectivity"
      summary: "creates or updates openconfig.transport.line.connectivity.lineconnectivitytop.Connections"
      description: "Enclosing container for line system connections list"
      parameters:
      - in: "body"
        name: "openconfig.transport.line.connectivity.lineconnectivitytop.Connections.body-param"
        description: "openconfig.transport.line.connectivity.lineconnectivitytop.Connections\
          \ to be added or updated"
        required: false
        schema:
          $ref: "#/definitions/openconfig.transport.line.connectivity.lineconnectivitytop.ConnectionsWrapper"
      responses:
        201:
          description: "Object created"
        400:
          description: "Internal error"
        204:
          description: "Object modified"
    delete:
      tags:
      - "openconfig-transport-line-connectivity"
      summary: "removes openconfig.transport.line.connectivity.lineconnectivitytop.Connections"
      description: "Enclosing container for line system connections list"
      parameters: []
      responses:
        400:
          description: "Internal error"
        204:
          description: "Object deleted"
  /data/connections/connection/:
    post:
      tags:
      - "openconfig-transport-line-connectivity"
      summary: "creates openconfig.transport.line.connectivity.lineconnectivitytop.connections.Connection"
      description: "List of line system connections"
      parameters:
      - in: "body"
        name: "openconfig.transport.line.connectivity.lineconnectivitytop.connections.Connection.body-param"
        description: "openconfig.transport.line.connectivity.lineconnectivitytop.connections.Connection\
          \ to be added to list"
        required: false
        schema:
          $ref: "#/definitions/openconfig.transport.line.connectivity.lineconnectivitytop.connections.ConnectionWrapper"
      responses:
        201:
          description: "Object created"
        400:
          description: "Internal error"
        409:
          description: "Object already exists"
  /data/connections/connection={index}:
    get:
      tags:
      - "openconfig-transport-line-connectivity"
      summary: "returns openconfig.transport.line.connectivity.lineconnectivitytop.connections.Connection"
      description: "List of line system connections"
      parameters:
      - name: "index"
        in: "path"
        description: "Id of connection"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "openconfig.transport.line.connectivity.lineconnectivitytop.connections.Connection"
          schema:
            $ref: "#/definitions/openconfig.transport.line.connectivity.lineconnectivitytop.connections.ConnectionWrapper"
        400:
          description: "Internal error"
    put:
      tags:
      - "openconfig-transport-line-connectivity"
      summary: "creates or updates openconfig.transport.line.connectivity.lineconnectivitytop.connections.Connection"
      description: "List of line system connections"
      parameters:
      - name: "index"
        in: "path"
        description: "Id of connection"
        required: true
        type: "integer"
        format: "int64"
      - in: "body"
        name: "openconfig.transport.line.connectivity.lineconnectivitytop.connections.Connection.body-param"
        description: "openconfig.transport.line.connectivity.lineconnectivitytop.connections.Connection\
          \ to be added or updated"
        required: false
        schema:
          $ref: "#/definitions/openconfig.transport.line.connectivity.lineconnectivitytop.connections.ConnectionWrapper"
      responses:
        201:
          description: "Object created"
        400:
          description: "Internal error"
        204:
          description: "Object modified"
    delete:
      tags:
      - "openconfig-transport-line-connectivity"
      summary: "removes openconfig.transport.line.connectivity.lineconnectivitytop.connections.Connection"
      description: "List of line system connections"
      parameters:
      - name: "index"
        in: "path"
        description: "Id of connection"
        required: true
        type: "integer"
        format: "int64"
      responses:
        400:
          description: "Internal error"
        204:
          description: "Object deleted"
  /data/connections/connection={index}/config:
    get:
      tags:
      - "openconfig-transport-line-connectivity"
      summary: "returns openconfig.transport.line.connectivity.ConnectionConfig"
      description: "Configuration data"
      parameters:
      - name: "index"
        in: "path"
        description: "Id of connection"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "openconfig.transport.line.connectivity.ConnectionConfig"
          schema:
            $ref: "#/definitions/openconfig.transport.line.connectivity.ConnectionConfigWrapper"
        400:
          description: "Internal error"
    post:
      tags:
      - "openconfig-transport-line-connectivity"
      summary: "creates openconfig.transport.line.connectivity.ConnectionConfig"
      description: "Configuration data"
      parameters:
      - name: "index"
        in: "path"
        description: "Id of connection"
        required: true
        type: "integer"
        format: "int64"
      - in: "body"
        name: "openconfig.transport.line.connectivity.ConnectionConfig.body-param"
        description: "openconfig.transport.line.connectivity.ConnectionConfig to be\
          \ added to list"
        required: false
        schema:
          $ref: "#/definitions/openconfig.transport.line.connectivity.ConnectionConfigWrapper"
      responses:
        201:
          description: "Object created"
        400:
          description: "Internal error"
        409:
          description: "Object already exists"
    put:
      tags:
      - "openconfig-transport-line-connectivity"
      summary: "creates or updates openconfig.transport.line.connectivity.ConnectionConfig"
      description: "Configuration data"
      parameters:
      - name: "index"
        in: "path"
        description: "Id of connection"
        required: true
        type: "integer"
        format: "int64"
      - in: "body"
        name: "openconfig.transport.line.connectivity.ConnectionConfig.body-param"
        description: "openconfig.transport.line.connectivity.ConnectionConfig to be\
          \ added or updated"
        required: false
        schema:
          $ref: "#/definitions/openconfig.transport.line.connectivity.ConnectionConfigWrapper"
      responses:
        201:
          description: "Object created"
        400:
          description: "Internal error"
        204:
          description: "Object modified"
    delete:
      tags:
      - "openconfig-transport-line-connectivity"
      summary: "removes openconfig.transport.line.connectivity.ConnectionConfig"
      description: "Configuration data"
      parameters:
      - name: "index"
        in: "path"
        description: "Id of connection"
        required: true
        type: "integer"
        format: "int64"
      responses:
        400:
          description: "Internal error"
        204:
          description: "Object deleted"
  /data/connections/connection={index}/state:
    get:
      tags:
      - "openconfig-transport-line-connectivity"
      summary: "returns openconfig.transport.line.connectivity.lineconnectivitytop.connections.connection.State"
      description: "Operational state data"
      parameters:
      - name: "index"
        in: "path"
        description: "Id of connection"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "openconfig.transport.line.connectivity.lineconnectivitytop.connections.connection.State"
          schema:
            $ref: "#/definitions/openconfig.transport.line.connectivity.lineconnectivitytop.connections.connection.StateWrapper"
        400:
          description: "Internal error"
definitions:
  openconfig.transport.line.connectivity.ConnectionConfig:
    type: "object"
    properties:
      index:
        type: "integer"
        format: "int64"
        description: "Index for the defined connection"
      source:
        type: "string"
        description: "The user supplied name of the source port of the connection\n\
          \        within the system. If the port is within the device, the\n\tstring\
          \ should reflect the name of the port as it appears in\n\tthe components\
          \ model. If the port is not represented in the\n\tcomponents model (e.g.,\
          \ a port on a passive chassis), the\n\tstring should reflect the system\
          \ assigned name of the port.\n\tIf the source port is not within the device,\
          \ then an\n\tidentityref of EXTERNAL should be specified."
      dest:
        type: "string"
        description: "The user supplied name of the destination port of the connection\n\
          \        within the system. If the port is within the device, the string\n\
          \tshould reflect the name of the port as it appears in the\n\tcomponents\
          \ model. If the port is not represented in the components\n\tmodel (e.g.,\
          \ a port on a passive chassis), the string should\n\treflect the system\
          \ assigned name of the port. If the destination\n\tport is not within the\
          \ device, then an identityref of EXTERNAL\n\tshould be specified."
      fiber-type:
        type: "string"
        description: "The type of fiber jumper used for the connection."
  openconfig.transport.line.connectivity.ConnectionConfigWrapper:
    properties:
      config:
        $ref: "#/definitions/openconfig.transport.line.connectivity.ConnectionConfig"
  openconfig.transport.line.connectivity.ConnectionState:
    type: "object"
  openconfig.transport.line.connectivity.lineconnectivitytop.Connections:
    type: "object"
    properties:
      connection:
        type: "array"
        description: "List of line system connections"
        items:
          $ref: "#/definitions/openconfig.transport.line.connectivity.lineconnectivitytop.connections.Connection"
  openconfig.transport.line.connectivity.lineconnectivitytop.ConnectionsWrapper:
    properties:
      connections:
        $ref: "#/definitions/openconfig.transport.line.connectivity.lineconnectivitytop.Connections"
  openconfig.transport.line.connectivity.lineconnectivitytop.connections.Connection:
    type: "object"
    properties:
      index:
        type: "integer"
        format: "int64"
        description: "Reference to index number of the connection"
        x-path: "../config/index"
      state:
        description: "Operational state data"
        $ref: "#/definitions/openconfig.transport.line.connectivity.lineconnectivitytop.connections.connection.State"
      config:
        description: "Configuration data"
        $ref: "#/definitions/openconfig.transport.line.connectivity.ConnectionConfig"
  openconfig.transport.line.connectivity.lineconnectivitytop.connections.ConnectionWrapper:
    properties:
      connection:
        $ref: "#/definitions/openconfig.transport.line.connectivity.lineconnectivitytop.connections.Connection"
  openconfig.transport.line.connectivity.lineconnectivitytop.connections.connection.State:
    allOf:
    - $ref: "#/definitions/openconfig.transport.line.connectivity.ConnectionConfig"
    - $ref: "#/definitions/openconfig.transport.line.connectivity.ConnectionState"
  openconfig.transport.line.connectivity.lineconnectivitytop.connections.connection.StateWrapper:
    properties:
      state:
        $ref: "#/definitions/openconfig.transport.line.connectivity.lineconnectivitytop.connections.connection.State"
