---
swagger: "2.0"
info:
  description: "Yang definitions for System Management.\n\n     Copyright of the Members\
    \ of the Open ROADM MSA Agreement dated (c) 2016,\n     All other rights reserved.\n\
    \n     Redistribution and use in source and binary forms, with or without modification,\n\
    \     are permitted provided that the following conditions are met:\n\n     *\
    \ Redistributions of source code must retain the above copyright notice, this\n\
    \       list of conditions and the following disclaimer.\n     * Redistributions\
    \ in binary form must reproduce the above copyright notice,\n       this list\
    \ of conditions and the following disclaimer in the documentation and/or\n   \
    \    other materials provided with the distribution.\n     * Neither the Members\
    \ of the Open ROADM MSA Agreement nor the names of its\n       contributors may\
    \ be used to endorse or promote products derived from this software\n       without\
    \ specific prior written permission.\n\n     THIS SOFTWARE IS PROVIDED BY THE\
    \ MEMBERS OF THE OPEN ROADM MSA  AGREEMENT ''AS IS''\n     AND ANY EXPRESS OR\
    \ IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED\n     WARRANTIES\
    \ OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.\n  \
    \   IN NO EVENT THE MEMBERS OF THE OPEN ROADM MSA  AGREEMENT BE LIABLE FOR ANY\
    \ DIRECT,\n     INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES\
    \ (INCLUDING, BUT\n     NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;\
    \  LOSS OF USE, DATA,\n     OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED\
    \ AND ON ANY THEORY OF LIABILITY,\n     WHETHER IN CONTRACT, STRICT LIABILITY,\
    \ OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)\n     ARISING IN ANY WAY OUT OF\
    \ THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE\n     POSSIBILITY OF SUCH DAMAGE."
  version: "1.0"
  title: "org-openroadm-swdl API"
host: "localhost:1234"
consumes:
- "application/yang-data+json"
produces:
- "application/yang-data+json"
paths:
  /operations/cancel-validation-timer:
    post:
      tags:
      - "org-openroadm-swdl"
      summary: "operates on org.openroadm.swdl.CancelValidationTimer"
      description: "operates on org.openroadm.swdl.CancelValidationTimer"
      parameters:
      - in: "body"
        name: "org.openroadm.swdl.cancelvalidationtimer.Input.body-param"
        required: false
        schema:
          properties:
            input:
              $ref: "#/definitions/org.openroadm.swdl.cancelvalidationtimer.Input"
      responses:
        200:
          description: "Correct response"
          schema:
            $ref: "#/definitions/org.openroadm.swdl.CancelValidationTimer"
        201:
          description: "No response"
        400:
          description: "Internal error"
  /operations/sw-activate:
    post:
      tags:
      - "org-openroadm-swdl"
      summary: "operates on org.openroadm.swdl.SwActivate"
      description: "operates on org.openroadm.swdl.SwActivate"
      parameters:
      - in: "body"
        name: "org.openroadm.swdl.swactivate.Input.body-param"
        required: false
        schema:
          properties:
            input:
              $ref: "#/definitions/org.openroadm.swdl.swactivate.Input"
      responses:
        200:
          description: "Correct response"
          schema:
            $ref: "#/definitions/org.openroadm.swdl.SwActivate"
        201:
          description: "No response"
        400:
          description: "Internal error"
  /operations/sw-stage:
    post:
      tags:
      - "org-openroadm-swdl"
      summary: "operates on org.openroadm.swdl.SwStage"
      description: "operates on org.openroadm.swdl.SwStage"
      parameters:
      - in: "body"
        name: "org.openroadm.swdl.swstage.Input.body-param"
        required: false
        schema:
          properties:
            input:
              $ref: "#/definitions/org.openroadm.swdl.swstage.Input"
      responses:
        200:
          description: "Correct response"
          schema:
            $ref: "#/definitions/org.openroadm.swdl.SwStage"
        201:
          description: "No response"
        400:
          description: "Internal error"
definitions:
  org.openroadm.common.types.RpcResponseStatus:
    type: "object"
    properties:
      status-message:
        type: "string"
        description: "Gives a more detailed status"
      status:
        description: "Successful or Failed"
        $ref: "#/definitions/org.openroadm.common.types.RpcStatus"
  org.openroadm.common.types.RpcStatus:
    type: "string"
    enum:
    - "Successful"
    - "Failed"
  org.openroadm.swdl.CancelValidationTimer:
    type: "object"
    properties:
      output:
        $ref: "#/definitions/org.openroadm.common.types.RpcResponseStatus"
  org.openroadm.swdl.SwActivate:
    type: "object"
    properties:
      output:
        $ref: "#/definitions/org.openroadm.common.types.RpcResponseStatus"
  org.openroadm.swdl.SwStage:
    type: "object"
    properties:
      output:
        $ref: "#/definitions/org.openroadm.common.types.RpcResponseStatus"
  org.openroadm.swdl.cancelvalidationtimer.Input:
    type: "object"
    properties:
      accept:
        type: "boolean"
        description: " TRUE means  validation timer is cancelled and new load is accepted"
        default: true
  org.openroadm.swdl.swactivate.Input:
    type: "object"
    properties:
      validationTimer:
        type: "string"
        description: "validation timer hh-mm-ss"
      version:
        type: "string"
        description: " software version of the new load which is being activated"
  org.openroadm.swdl.swstage.Input:
    type: "object"
    properties:
      filename:
        type: "string"
        description: "file name which has the load"
