---
swagger: "2.0"
info:
  description: "YANG definitions for file management related rpcs.\n\n     Copyright\
    \ of the Members of the Open ROADM MSA Agreement dated (c) 2016,\n     All other\
    \ rights reserved.\n\n     Redistribution and use in source and binary forms,\
    \ with or without modification,\n     are permitted provided that the following\
    \ conditions are met:\n\n     * Redistributions of source code must retain the\
    \ above copyright notice, this\n       list of conditions and the following disclaimer.\n\
    \     * Redistributions in binary form must reproduce the above copyright notice,\n\
    \       this list of conditions and the following disclaimer in the documentation\
    \ and/or\n       other materials provided with the distribution.\n     * Neither\
    \ the Members of the Open ROADM MSA Agreement nor the names of its\n       contributors\
    \ may be used to endorse or promote products derived from this software\n    \
    \   without specific prior written permission.\n\n     THIS SOFTWARE IS PROVIDED\
    \ BY THE MEMBERS OF THE OPEN ROADM MSA  AGREEMENT ''AS IS''\n     AND ANY EXPRESS\
    \ OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED\n     WARRANTIES\
    \ OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.\n  \
    \   IN NO EVENT THE MEMBERS OF THE OPEN ROADM MSA  AGREEMENT BE LIABLE FOR ANY\
    \ DIRECT,\n     INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES\
    \ (INCLUDING, BUT\n     NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;\
    \  LOSS OF USE, DATA,\n     OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED\
    \ AND ON ANY THEORY OF LIABILITY,\n     WHETHER IN CONTRACT, STRICT LIABILITY,\
    \ OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)\n     ARISING IN ANY WAY OUT OF\
    \ THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE\n     POSSIBILITY OF SUCH DAMAGE."
  version: "1.0"
  title: "org-openroadm-file-transfer API"
host: "localhost:1234"
consumes:
- "application/yang-data+json"
produces:
- "application/yang-data+json"
paths:
  /operations/delete-file:
    post:
      tags:
      - "org-openroadm-file-transfer"
      summary: "operates on org.openroadm.file.transfer.DeleteFile"
      description: "operates on org.openroadm.file.transfer.DeleteFile"
      parameters:
      - in: "body"
        name: "org.openroadm.file.transfer.deletefile.Input.body-param"
        required: false
        schema:
          properties:
            input:
              $ref: "#/definitions/org.openroadm.file.transfer.deletefile.Input"
      responses:
        200:
          description: "Correct response"
          schema:
            $ref: "#/definitions/org.openroadm.file.transfer.DeleteFile"
        201:
          description: "No response"
        400:
          description: "Internal error"
  /operations/show-file:
    post:
      tags:
      - "org-openroadm-file-transfer"
      summary: "operates on org.openroadm.file.transfer.ShowFile"
      description: "operates on org.openroadm.file.transfer.ShowFile"
      parameters:
      - in: "body"
        name: "org.openroadm.file.transfer.showfile.Input.body-param"
        required: false
        schema:
          properties:
            input:
              $ref: "#/definitions/org.openroadm.file.transfer.showfile.Input"
      responses:
        200:
          description: "Correct response"
          schema:
            $ref: "#/definitions/org.openroadm.file.transfer.ShowFile"
        201:
          description: "No response"
        400:
          description: "Internal error"
  /operations/transfer:
    post:
      tags:
      - "org-openroadm-file-transfer"
      summary: "operates on org.openroadm.file.transfer.Transfer"
      description: "operates on org.openroadm.file.transfer.Transfer"
      parameters:
      - in: "body"
        name: "org.openroadm.file.transfer.transfer.Input.body-param"
        required: false
        schema:
          properties:
            input:
              $ref: "#/definitions/org.openroadm.file.transfer.transfer.Input"
      responses:
        200:
          description: "Correct response"
          schema:
            $ref: "#/definitions/org.openroadm.file.transfer.Transfer"
        201:
          description: "No response"
        400:
          description: "Internal error"
definitions:
  org.openroadm.common.types.RpcResponseStatus:
    type: "object"
    properties:
      status-message:
        type: "string"
        description: "Gives a more detailed status"
      status:
        description: "Successful or Failed"
        $ref: "#/definitions/org.openroadm.common.types.RpcStatus"
  org.openroadm.common.types.RpcStatus:
    type: "string"
    enum:
    - "Successful"
    - "Failed"
  org.openroadm.file.transfer.ActionEnumeration:
    type: "string"
    enum:
    - "upload"
    - "download"
    - "onekey-upgrading"
  org.openroadm.file.transfer.DeleteFile:
    type: "object"
    properties:
      output:
        $ref: "#/definitions/org.openroadm.common.types.RpcResponseStatus"
  org.openroadm.file.transfer.ShowFile:
    type: "object"
    properties:
      output:
        $ref: "#/definitions/org.openroadm.file.transfer.showfile.Output"
  org.openroadm.file.transfer.Transfer:
    type: "object"
    properties:
      output:
        $ref: "#/definitions/org.openroadm.common.types.RpcResponseStatus"
  org.openroadm.file.transfer.deletefile.Input:
    type: "object"
    properties:
      filename:
        type: "string"
        description: "Specify file to be deleted.  Implementations may optionally\
          \ support * as a wildcard."
  org.openroadm.file.transfer.showfile.Input:
    type: "object"
    properties:
      filename:
        type: "string"
        description: "Specify file(s) to be listed (* is allowed as wild-card). "
        default: "*"
  org.openroadm.file.transfer.showfile.Output:
    type: "object"
    properties:
      file:
        type: "array"
        description: "output file list"
        items:
          $ref: "#/definitions/org.openroadm.file.transfer.showfile.output.File"
      status-message:
        type: "string"
        description: "status message"
      status:
        description: "RPC status"
        $ref: "#/definitions/org.openroadm.common.types.RpcStatus"
  org.openroadm.file.transfer.showfile.output.File:
    type: "object"
    properties:
      file-size:
        type: "integer"
        format: "int32"
        description: "output file size"
      modified-date:
        type: "string"
        description: "output modified date"
      filename:
        type: "string"
        description: "output filename"
  org.openroadm.file.transfer.transfer.Input:
    type: "object"
    properties:
      remote-file-path:
        type: "string"
        description: "Remote file path.\n           A URI for the remote file path.\n\
          \n           Format:sftp://user[:password]@host[:port]/path.\n         \
          \  Ex: sftp://test:verify@[2001:db8:0:1::10]:22/home/user/sample"
      action:
        description: "Type of action - download/upload."
        $ref: "#/definitions/org.openroadm.file.transfer.ActionEnumeration"
      local-file-path:
        type: "string"
        description: "Local file path.\n           Ex: /var/shared/example.txt"
