---
swagger: "2.0"
info:
  description: "YANG definitions of operations.\n\n     Copyright of the Members of\
    \ the Open ROADM MSA Agreement dated (c) 2016,\n     All other rights reserved.\n\
    \n     Redistribution and use in source and binary forms, with or without modification,\n\
    \     are permitted provided that the following conditions are met:\n\n     *\
    \ Redistributions of source code must retain the above copyright notice, this\n\
    \       list of conditions and the following disclaimer.\n     * Redistributions\
    \ in binary form must reproduce the above copyright notice,\n       this list\
    \ of conditions and the following disclaimer in the documentation and/or\n   \
    \    other materials provided with the distribution.\n     * Neither the Members\
    \ of the Open ROADM MSA Agreement nor the names of its\n       contributors may\
    \ be used to endorse or promote products derived from this software\n       without\
    \ specific prior written permission.\n\n     THIS SOFTWARE IS PROVIDED BY THE\
    \ MEMBERS OF THE OPEN ROADM MSA  AGREEMENT ''AS IS''\n     AND ANY EXPRESS OR\
    \ IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED\n     WARRANTIES\
    \ OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.\n  \
    \   IN NO EVENT THE MEMBERS OF THE OPEN ROADM MSA  AGREEMENT BE LIABLE FOR ANY\
    \ DIRECT,\n     INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES\
    \ (INCLUDING, BUT\n     NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;\
    \  LOSS OF USE, DATA,\n     OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED\
    \ AND ON ANY THEORY OF LIABILITY,\n     WHETHER IN CONTRACT, STRICT LIABILITY,\
    \ OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)\n     ARISING IN ANY WAY OUT OF\
    \ THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE\n     POSSIBILITY OF SUCH DAMAGE."
  version: "1.0"
  title: "org-openroadm-de-operations API"
host: "localhost:1234"
consumes:
- "application/yang-data+json"
produces:
- "application/yang-data+json"
paths:
  /operations/restart:
    post:
      tags:
      - "org-openroadm-de-operations"
      summary: "operates on org.openroadm.de.operations.Restart"
      description: "operates on org.openroadm.de.operations.Restart"
      parameters:
      - in: "body"
        name: "org.openroadm.de.operations.restart.Input.body-param"
        required: false
        schema:
          properties:
            input:
              $ref: "#/definitions/org.openroadm.de.operations.restart.Input"
      responses:
        200:
          description: "Correct response"
          schema:
            $ref: "#/definitions/org.openroadm.de.operations.Restart"
        201:
          description: "No response"
        400:
          description: "Internal error"
definitions:
  org.openroadm.common.types.RpcResponseStatus:
    type: "object"
    properties:
      status-message:
        type: "string"
        description: "Gives a more detailed status"
      status:
        description: "Successful or Failed"
        $ref: "#/definitions/org.openroadm.common.types.RpcStatus"
  org.openroadm.common.types.RpcStatus:
    type: "string"
    enum:
    - "Successful"
    - "Failed"
  org.openroadm.de.operations.OptionEnumeration:
    type: "string"
    enum:
    - "warm"
    - "cold"
  org.openroadm.de.operations.Restart:
    type: "object"
    properties:
      output:
        $ref: "#/definitions/org.openroadm.common.types.RpcResponseStatus"
  org.openroadm.de.operations.restart.Input:
    allOf:
    - $ref: "#/definitions/org.openroadm.resource.Resource"
    - type: "object"
      properties:
        option:
          $ref: "#/definitions/org.openroadm.de.operations.OptionEnumeration"
  org.openroadm.resource.Resource:
    type: "object"
    properties:
      resource:
        $ref: "#/definitions/org.openroadm.resource.resource.Resource"
      device:
        description: "Device of the resource, used only when the system using this\n\
          \         model report on more than one device. "
        $ref: "#/definitions/org.openroadm.resource.types.DeviceId"
      resourceType:
        $ref: "#/definitions/org.openroadm.resource.types.ResourceType"
  org.openroadm.resource.resource.Resource:
    type: "object"
    properties:
      node-id:
        type: "string"
        description: "Node Id is a globally unique identifier for a device.\n    \
          \     Same as leafref value in model, if applicable."
        x-choice: "resource:device"
      connection-name:
        type: "string"
        description: "Connection name. Unique within the context of a device.\n  \
          \       Same as leafref value in model, if applicable."
        x-choice: "resource:connection"
      internal-link-name:
        type: "string"
        description: "Internal Link identifier. Unique within the context of a device.\n\
          \         Same as leafref value in model, if applicable."
        x-choice: "resource:internal-link"
      interface-name:
        type: "string"
        description: "Interface identifier."
        x-choice: "resource:interface"
      versioned-service-name:
        type: "string"
        description: "Service identifier. Unique within the context of a network.\n\
          \         Same as leafref value in model, if applicable."
        x-choice: "resource:versioned-service"
      odu-sncp-pg-name:
        type: "string"
        description: "name of the odu-snc-pg"
        x-choice: "resource:odu-sncp-pg"
      circuit-pack-name:
        type: "string"
        description: "Circuit-Pack identifier. Unique within the context of a device.\n\
          \         Same as leafref value in model, if applicable."
        x-choice: "resource:circuit-pack"
      degree-number:
        type: "integer"
        format: "int32"
        description: "Degree identifier. Unique within the context of a device.\n\
          \         Same as leafref value in model, if applicable."
        x-choice: "resource:degree"
      srg-number:
        type: "integer"
        format: "int32"
        description: "Shared Risk Group identifier. Unique within the context of a\
          \ device.\n         Same as leafref value in model, if applicable."
        x-choice: "resource:srg"
      shelf-name:
        type: "string"
        description: "Shelf-id identifier. Unique within the context of a device.\n\
          \         Same as leafref value in model, if applicable."
        x-choice: "resource:shelf"
      service-name:
        type: "string"
        description: "Service identifier. Unique within the context of a network.\n\
          \         Same as leafref value in model, if applicable."
        x-choice: "resource:service"
      common-id:
        type: "string"
        description: "Service identifier. Unique within the context of a network.\n\
          \         Same as leafref value in model, if applicable."
        x-choice: "resource:temp-service"
      physical-link-name:
        type: "string"
        description: "Physical Link identifier. Unique within the context of a device.\n\
          \         Same as leafref value in model, if applicable."
        x-choice: "resource:physical-link"
      port:
        $ref: "#/definitions/org.openroadm.resource.types.PortName"
        x-choice: "resource:port"
      other-resource-id:
        type: "string"
        description: "resource-id for other."
        x-choice: "resource:other"
      xpdr-number:
        type: "integer"
        format: "int32"
        description: "number of the xponder"
        x-choice: "resource:xponder"
      version-number:
        type: "integer"
        format: "int32"
        description: "version-number of the service"
        x-choice: "resource:versioned-service"
      amp-number:
        type: "integer"
        format: "int32"
        description: "number of the line-amplifier"
        x-choice: "resource:line-amplifier"
  org.openroadm.resource.types.CircuitPackName:
    type: "object"
    properties:
      circuit-pack-name:
        type: "string"
        description: "Circuit-Pack identifier. Unique within the context of a device.\n\
          \         Same as leafref value in model, if applicable."
  org.openroadm.resource.types.DeviceId:
    type: "object"
    properties:
      node-id:
        type: "string"
        description: "Node Id is a globally unique identifier for a device.\n    \
          \     Same as leafref value in model, if applicable."
  org.openroadm.resource.types.PortName:
    allOf:
    - $ref: "#/definitions/org.openroadm.resource.types.CircuitPackName"
    - type: "object"
      properties:
        port-name:
          type: "string"
          description: "Port identifier. Unique within the context of a circuit-pack.\n\
            \         Same as leafref value in model, if applicable."
  org.openroadm.resource.types.ResourceType:
    type: "object"
    properties:
      type:
        $ref: "#/definitions/org.openroadm.resource.types.ResourceTypeEnum"
      extension:
        type: "string"
  org.openroadm.resource.types.ResourceTypeEnum:
    type: "string"
    enum:
    - "other"
    - "device"
    - "degree"
    - "shared-risk-group"
    - "connection"
    - "connection-map"
    - "port"
    - "circuit-pack"
    - "internal-link"
    - "physical-link"
    - "interface"
    - "shelf"
    - "service"
    - "odu-sncp-pg"
    - "line-amplifier"
    - "xponder"
    - "versioned-service"
    - "temp-service"
